### GET ### user list
GET http://localhost:4000/api/auth/list HTTP/1.1


### POST ### login dmcho84@gmail.com
POST http://localhost:4000/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "dmcho84@gmail.com",
    "password": "12345",
    "time": "Sat, 14 Apr 2018 09:29:08 GMT"
}

### POST ### login junishop@gmail.com
POST http://localhost:4000/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "junishop@gmail.com",
    "password": "12345",
    "time": "Sat, 14 Apr 2018 09:29:08 GMT"
}

### POST ### login marlboro2006@naver.com
POST http://localhost:4000/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "marlboro2006@naver.com",
    "password": "54321",
    "time": "Sat, 14 Apr 2018 09:29:08 GMT"
}


### POST ### login marlboro2006@naver.com
POST http://localhost:4000/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "test@naver.com",
    "password": "32098430598",
    "time": "Sat, 14 Apr 2018 09:29:08 GMT"
}

### POST ### Join 
POST http://localhost:4000/api/auth/join HTTP/1.1
content-type: application/json

{
    "name": "asdasd",
    "email": "test@naver.com",
    "password": "32098430598",
    "time": "Sat, 14 Apr 2018 09:29:08 GMT"
}

### DELETE ### Delete 
DELETE http://localhost:4000/api/auth/5ad84986e06ea51facd0b516 HTTP/1.1
content-type: application/json

{
    "name": "asdasd",
    "email": "test@naver.com",
    "password": "32098430598",
    "time": "Sat, 14 Apr 2018 09:29:08 GMT"
}
